package com.lab.island.ui.theme

import androidx.compose.ui.graphics.Color

val SkyBlueLight = Color(0xFF1976D2)
val OnSkyBlueLight = Color(0xFFFFFFFF)
val SkyBlueContainerLight = Color(0xFFD6E9FF)
val OnSkyBlueContainerLight = Color(0xFF001D36)
val SkyInversePrimaryLight = Color(0xFFA4CCFF)
val SkySecondaryLight = Color(0xFF535F70)
val OnSkySecondaryLight = Color(0xFFFFFFFF)
val SkySecondaryContainerLight = Color(0xFFD7E3F8)
val OnSkySecondaryContainerLight = Color(0xFF101C2B)
val SkyTertiaryLight = Color(0xFF3C6474)
val OnSkyTertiaryLight = Color(0xFFFFFFFF)
val SkyTertiaryContainerLight = Color(0xFFC1E9FA)
val OnSkyTertiaryContainerLight = Color(0xFF001F29)
val SkyBackgroundLight = Color(0xFFF8F9FF)
val SkySurfaceLight = Color(0xFFF8F9FF)
val SkySurfaceVariantLight = Color(0xFFDFE3EB)
val OnSkySurfaceVariantLight = Color(0xFF42474E)
val SkyOutlineLight = Color(0xFF73777F)
val SkyOutlineVariantLight = Color(0xFFC2C7CF)
val SkySurfaceDimLight = Color(0xFFD8DAE0)
val SkySurfaceBrightLight = Color(0xFFF8F9FF)
val SkySurfaceContainerLowestLight = Color(0xFFFFFFFF)
val SkySurfaceContainerLowLight = Color(0xFFF2F3F9)
val SkySurfaceContainerLight = Color(0xFFECEEF4)
val SkySurfaceContainerHighLight = Color(0xFFE6E8EE)
val SkySurfaceContainerHighestLight = Color(0xFFE0E2E8)

val SkyBlueDark = Color(0xFFA4CCFF)
val OnSkyBlueDark = Color(0xFF003258)
val SkyBlueContainerDark = Color(0xFF00497D)
val OnSkyBlueContainerDark = Color(0xFFD6E9FF)
val SkyInversePrimaryDark = Color(0xFF1976D2)
val SkySecondaryDark = Color(0xFFBBC7DB)
val OnSkySecondaryDark = Color(0xFF263141)
val SkySecondaryContainerDark = Color(0xFF3C4858)
val OnSkySecondaryContainerDark = Color(0xFFD7E3F8)
val SkyTertiaryDark = Color(0xFFA5CDDD)
val OnSkyTertiaryDark = Color(0xFF073542)
val SkyTertiaryContainerDark = Color(0xFF254C5A)
val OnSkyTertiaryContainerDark = Color(0xFFC1E9FA)
val SkyBackgroundDark = Color(0xFF101418)
val SkySurfaceDark = Color(0xFF101418)
val SkySurfaceVariantDark = Color(0xFF42474E)
val OnSkySurfaceVariantDark = Color(0xFFC2C7CF)
val SkyOutlineDark = Color(0xFF8C9199)
val SkyOutlineVariantDark = Color(0xFF42474E)
val SkySurfaceDimDark = Color(0xFF101418)
val SkySurfaceBrightDark = Color(0xFF363A3F)
val SkySurfaceContainerLowestDark = Color(0xFF0B0F13)
val SkySurfaceContainerLowDark = Color(0xFF181C20)
val SkySurfaceContainerDark = Color(0xFF1C2024)
val SkySurfaceContainerHighDark = Color(0xFF272A2F)
val SkySurfaceContainerHighestDark = Color(0xFF32353A)
